{% set name = "thermotools" %}
{% set version = "0.2.7" %}
{% set sha256 = "34e492f2593428fbd3f4d9b67a9283bfa6d9bb1f6392e898e10093a11c7af250" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
 
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - msmtools >=1.1.4

test:
  imports:
    - thermotools

about:
  home: http://github.com/markovmodel/thermotools
  license: LGPL3+
  license_file: COPYING.LESSER
  summary: 'Lowlevel implementation of (transition-based and histogram) reweighting analyis methods for Python.'

  description: |
    The thermotools package is a lowlevel implementation toolbox for the analyis
    of multi-ensemble calculations. It contains estimators for the state-continuous transition-based
    reweighting analysis method (TRAM) and its state-discrete variant (dTRAM), Bennet acceptance ratio
    (BAR) and its multi-state variant (MBAR), and the weighted histogram analysis method (WHAM).
    While you can use thermotools on its own, we recommend to use it in combination with PyEMMA.
  dev_url: https://github.com/markovmodel/thermotools

extra:
  recipe-maintainers:
    - marscher
    - fabian-paul
    - cwehmeyer
