appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 1Lcjoi2UD3gLKnSS4FER0a5fQpvNqZUy0sHV11S7uld+SYo4P9RBPvHcwzDhbsuEGsrsEw5Wiay3Q1dtzjJQ2VZeps996obn7AVn9bRvG60uD8LApRWktt5GPRUFhpRjWjpZYIKuhysHGdzlV/wE0D5PP0TDDyj3dnrF6yiWt7CBqfqxSK8Av27x84Lz6oZcd90nCbondLKS7VnsgEN1fFifWC5/BiCECmg3fpoKoG9sxU4OfLowv9bLLTXMsH6X6Ghj05JHcJ4eli6auQboa7xrehu3sPAU51w3SsdtjNbrP5MeqdttHPNvTXtTdu3OkCR+ZC4KR4rSAar3VI6xjMbkuGpExsYraJ803eetaY74nkxW0sLzL7+P8r9cL9edJ3eblt2Rnyvxs8YLkiI5/E9h4MsuPkbZsT+yzNzb1GuZDkuDRobJzpUBGWYOZvBd+bWN6O/rInp4OVqnPykpIYCP+YKFsX7/sRfHQDnTv/pqosUXgrloq+2xmzKILd/CzI/Mz9IdH+O8w0jdGbFNwR93wWId11lE2cJ0QjWe4HNflJqCnuqBiPtZdIC6KbCeh+Ru2Xlfdto0s3s1WDYMrUVjVm6HeJU0NvzJ/aowc91spa+/N68LgsV7EsAchmPPa8DtON/LwEZ5dpN9k2zu19T9YPITuOfdH59JcRlGjnE=}
conda_forge_output_validation: false
